version: '3.4'

services:
  backend:
    image: backend
    build:
      context: backend/monolith
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
