version: '3'

services:
  # lb:
  #   image:  haproxy:alpine
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  #   depends_on: 
  #     - post1
  #     - post2
  auth:
    build: ./auth/.
    volumes:
      - ./auth/.:/usr/src/app/serve
    links:
      - mongo
  post:
    build: ./post/.
    volumes:
      - ./post/.:/usr/src/app/server
    links:
      - mongo
  profile:
    build: ./profile/.
    volumes:
      - ./profile/.:/usr/src/app/server
    links:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - post
      - profile
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: qw123456
  #  auth_db:
  #    image: mongo
  #    restart: always
  #    volumes:
  #      - data:/data/db
   
  #  post_db:
  #    image: mongo
  #    restart: always
  #    volumes:
  #      - data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root1
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: root

volumes:
  data: